# Generated by Django 3.1.2 on 2020-11-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0002_auto_20201115_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='historial_medico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
