# Generated by Django 3.1.2 on 2020-11-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0004_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_del_pedido',
            field=models.PositiveSmallIntegerField(choices=[(1, 'pendiente'), (2, 'taller'), (3, 'pedido')], default=1),
        ),
    ]
