# Generated by Django 3.1.2 on 2020-11-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0005_pedido_estado_del_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_del_pedido',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('taller', 'taller'), ('pedido', 'pedido')], default='pendiente', max_length=50),
        ),
    ]
