# Generated by Django 3.1.2 on 2020-11-16 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0006_auto_20201116_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_producto',
            field=models.CharField(choices=[('cerca', 'cerca'), ('lejos', 'lejos')], default='cerca', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinicaApp.producto'),
        ),
    ]
