# Generated by Django 3.1.2 on 2020-11-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0007_auto_20201116_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='tipo_producto',
        ),
    ]
