# Generated by Django 3.1.2 on 2020-11-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0008_remove_pedido_tipo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_del_pedido',
            field=models.CharField(blank=True, choices=[('pendiente', 'pendiente'), ('taller', 'taller'), ('pedido', 'pedido')], default='pendiente', max_length=50, null=True),
        ),
    ]
