# Generated by Django 3.1.2 on 2020-11-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0009_auto_20201116_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='nombre',
            new_name='producto',
        ),
    ]
