# Generated by Django 3.1.2 on 2020-11-17 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0010_auto_20201117_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinicaApp.paciente'),
        ),
    ]
