# Generated by Django 3.1.2 on 2020-11-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0013_auto_20201117_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipoLado',
            field=models.CharField(blank=True, choices=[('izquierda', 'izquierda'), ('derecha', 'derecha')], default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipoMarco',
            field=models.CharField(blank=True, choices=[('si', 'si'), ('no', 'no')], default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipoProducto',
            field=models.CharField(blank=True, choices=[('cerca', 'cerca'), ('lejos', 'lejos')], default='', max_length=20, null=True),
        ),
    ]
