# Generated by Django 3.1.2 on 2020-11-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0016_auto_20201118_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
