# Generated by Django 3.1.2 on 2020-11-19 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0017_remove_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinicaApp.paciente'),
        ),
    ]
