# Generated by Django 3.1.2 on 2020-11-19 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0018_auto_20201118_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'paciente', 'verbose_name_plural': 'pacientes'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinicaApp.paciente'),
        ),
    ]
