# Generated by Django 3.1.2 on 2020-11-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0019_auto_20201118_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
