# Generated by Django 3.1.2 on 2020-11-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0020_auto_20201119_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
