# Generated by Django 3.1.2 on 2020-11-19 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0021_auto_20201119_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial_medico', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'historial_medico',
                'verbose_name_plural': 'historiales_medicos',
            },
        ),
        migrations.AlterField(
            model_name='paciente',
            name='historial_medico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicaApp.historial_medico'),
        ),
    ]
