# Generated by Django 3.1.2 on 2020-11-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0024_auto_20201119_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_medico',
            name='historial_medico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
