# Generated by Django 3.1.2 on 2020-11-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0026_auto_20201119_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial_medico',
            old_name='historial_id',
            new_name='paciente',
        ),
    ]
