# Generated by Django 3.1.2 on 2020-11-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0027_auto_20201120_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medico', to='clinicaApp.medico'),
        ),
    ]
