# Generated by Django 3.1.2 on 2020-11-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0028_auto_20201120_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='hora',
        ),
    ]
