# Generated by Django 3.1.2 on 2020-11-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0034_auto_20201123_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_del_pedido',
            field=models.CharField(blank=True, choices=[('pendiente', 'pendiente'), ('taller', 'taller'), ('pedido', 'pedido'), ('finalizafo', 'finalizado')], default='pendiente', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='concurrio',
            field=models.CharField(blank=True, choices=[('si', 'si'), ('no', 'no'), ('pendiente', 'pendiente')], default='pendiente', max_length=20, null=True),
        ),
    ]
