# Generated by Django 3.1.2 on 2020-11-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0036_auto_20201123_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
