# Generated by Django 3.1.2 on 2020-11-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0037_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formaPago', models.CharField(blank=True, choices=[('Credito', 'Credito'), ('Debito', 'Debito'), ('Villetera virtual', 'Billetera virtual'), ('Efectivo', 'Efectivo')], default='Efectivo', max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_del_pedido',
            field=models.CharField(blank=True, choices=[('pendiente', 'pendiente'), ('taller', 'taller'), ('pedido', 'pedido')], default='pendiente', max_length=50, null=True),
        ),
    ]
