# Generated by Django 3.1.2 on 2020-11-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0038_auto_20201125_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormaPago',
        ),
        migrations.AddField(
            model_name='pedido',
            name='formaPago',
            field=models.CharField(blank=True, choices=[('Credito', 'Credito'), ('Debito', 'Debito'), ('Villetera virtual', 'Billetera virtual'), ('Efectivo', 'Efectivo')], default='Efectivo', max_length=50, null=True),
        ),
    ]
