# Generated by Django 3.1.2 on 2020-11-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0039_auto_20201125_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='ultimaVisita',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
