# Generated by Django 3.1.2 on 2020-11-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0040_turno_ultimavisita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_del_pedido',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('taller', 'Taller'), ('pedido', 'Pedido'), ('finalizado', 'Finalizado')], default='pendiente', max_length=50, null=True),
        ),
    ]
