# Generated by Django 3.1.2 on 2020-11-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0041_auto_20201126_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'permissions': (('view_precio', 'Puede ver el precio'),), 'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
    ]
