# Generated by Django 3.1.2 on 2020-11-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0043_permisos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name': 'pedido', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.AlterModelOptions(
            name='permisos',
            options={'permissions': (('view_gerencia', 'Puede ver el gerencia'), ('view_precio', 'Puede ver el precio'), ('view_paciente_secre', 'Puede ver el pacientes '))},
        ),
    ]
