# Generated by Django 3.1.2 on 2020-12-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0044_auto_20201128_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='tipoProducto',
            new_name='Cerca_Lejos',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='tipoLado',
            new_name='Derecha_Izquierda',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='tipoMarco',
            new_name='Marco',
        ),
    ]
