# Generated by Django 3.1.2 on 2020-12-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaApp', '0045_auto_20201201_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='Cerca_Lejos',
            new_name='Cerca_o_Lejos',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='Derecha_Izquierda',
            new_name='Derecha_o_Izquierda',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='formaPago',
            new_name='forma_de_Pago',
        ),
    ]
